version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: task-backend
    restart: unless-stopped
    env_file:
      - ./backend/config.env
    ports:
      - "3009:3009"
    networks:
      - task-network

  frontend:
    build:
      context: ./frontend
    container_name: task-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - task-network

networks:
  task-network:
    driver: bridge