export default {
  login: "/api/auth/v1/login",
  logout: "/api/auth/v1/logout",
  refreshtokkenEndpoint :"/api/auth/v1/refresh",
  getProfile: "/api/user/v1/profile",
  curdCompanyEndpoint: "/api/auth/v1/companies",
  curdUsersEndpoint: "/api/auth/v1/users",
  getallUser:"/api/auth/v1/getusers",
  setPasswordEndpoint: "/api/auth/v1/set_password",
  curdProjectEndpoint: "/api/auth/v1/project",
  markdefaultProject: "/api/auth/v1/project/markdefaultproject",
  markLastPreferenceProject: "/api/auth/v1/project/lastPreferenceproject",
  curdSprintEndpoint: "/api/auth/v1/sprint",
  markdefaultSprint: "/api/auth/v1/project/markdefaultsprint",
  curdTaskEndpoint: "/api/auth/v1/task",
  curdTagEndpoint: "/api/auth/v1/tag",
  curdkanbanTaskColumn: "/api/auth/vi/kanbancolumn",
  mediauploaderaws : "/api/auth/v1/mediauploader",
  taskActivityEndpont :"/api/auth/v1/taskActivity",
  dashboardempSummaryWidget :"/api/auth/vi/dashboard/summaryemp",
  dashboardadminSummaryWidget :"/api/auth/vi/dashboard/summaryadmin",
  notificationEndpoint:"/api/auth/vi/notification",
  readnotificationEndpoint:"/api/auth/vi/notification/read",
  getdeletedTaskEndpoint :"/api/auth/v1/task/deletedtask",
};
