// dashboardStyles.js
export const S = {
  card:       { background: "#fff", border: "1px solid #ebebeb", borderRadius: 12, padding: 18, width: "100%", boxSizing: "border-box" },
  header:     { display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 16, gap: 12, flexWrap: "wrap" },
  title:      { fontSize: 14, fontWeight: 500, color: "#111", margin: "0 0 3px" },
  sub:        { fontSize: 11, color: "#aaa", margin: 0 },
  legend:     { display: "flex", gap: 10, flexWrap: "wrap" },
  legendItem: { display: "flex", alignItems: "center", gap: 5, fontSize: 11, color: "#666" },
  legendDot:  { width: 8, height: 8, borderRadius: 2, flexShrink: 0 },
  divider:    { height: 1, background: "#f5f5f5", margin: "12px 0" },
  row:        { display: "grid", gridTemplateColumns: "140px 1fr auto", alignItems: "center", gap: 12, cursor: "pointer" },
  nameWrap:   { display: "flex", alignItems: "center", gap: 8, minWidth: 0 },
  avatar:     { width: 26, height: 26, borderRadius: "50%", background: "#ECEAFD", color: "#7367f0", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 9, fontWeight: 600, flexShrink: 0 },
  name:       { fontSize: 12, color: "#333", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  track:      { width: "100%", height: 8, background: "#f0f0f0", borderRadius: 999, overflow: "hidden", display: "flex" },
  fill:       { height: "100%", borderRadius: 999, transition: "width 0.3s ease" },
  centerLabel:{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", textAlign: "center", pointerEvents: "none", display: "flex", flexDirection: "column", alignItems: "center" },
  centerVal:  { fontSize: 22, fontWeight: 500, color: "#7367f0", lineHeight: 1 },
  centerSub:  { fontSize: 10, color: "#aaa", marginTop: 3 },
  statRow:    { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 0", cursor: "pointer", borderBottom: "1px solid #f5f5f5" },
  typeRow:    { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 },
  typeChip:   { display: "flex", alignItems: "center", gap: 5, padding: "5px 10px", borderRadius: 20 },
  typeChipDot:{ width: 6, height: 6, borderRadius: "50%", flexShrink: 0 },
  priorityDot:{ fontSize: 10, fontWeight: 500, padding: "2px 8px", borderRadius: 20, whiteSpace: "nowrap" },
};